--------------------------------------------------------
--  Arquivo criado - sábado-maio-31-2025
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence TB_CLIENTE3_ID_CLIENTE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "GLOBAL"."TB_CLIENTE3_ID_CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TB_CONTATO3_ID_CONTATO_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "GLOBAL"."TB_CONTATO3_ID_CONTATO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TB_ENDERECO3_ID_ENDERECO_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "GLOBAL"."TB_ENDERECO3_ID_ENDERECO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TB_EONET3_ID_EONET_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "GLOBAL"."TB_EONET3_ID_EONET_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table TB_CLIENTECONTATO3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_CLIENTECONTATO3"
(	"TB_CLIENTE3_ID_CLIENTE" NUMBER,
     "TB_CONTATO3_ID_CONTATO" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_CLIENTEENDERECO3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_CLIENTEENDERECO3"
(	"TB_CLIENTE3_ID_CLIENTE" NUMBER,
     "TB_ENDERECO3_ID_ENDERECO" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_CLIENTE3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_CLIENTE3"
(	"DATA_NASCIMENTO" VARCHAR2(10 BYTE),
     "SOBRENOME" VARCHAR2(100 BYTE),
     "DOCUMENTO" VARCHAR2(18 BYTE),
     "ID_CLIENTE" NUMBER,
     "NOME" VARCHAR2(100 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_CONTATO3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_CONTATO3"
(	"ID_CONTATO" NUMBER,
     "DDD" VARCHAR2(3 BYTE),
     "TELEFONE" VARCHAR2(15 BYTE),
     "CELULAR" VARCHAR2(15 BYTE),
     "WHATSAPP" VARCHAR2(15 BYTE),
     "EMAIL" VARCHAR2(255 BYTE),
     "TIPO_CONTATO" VARCHAR2(50 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_ENDERECOEVENTOS3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_ENDERECOEVENTOS3"
(	"TB_ENDERECO3_ID_ENDERECO" NUMBER,
     "TB_EONET3_ID_EONET" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_ENDERECO3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_ENDERECO3"
(	"ID_ENDERECO" NUMBER,
     "CEP" VARCHAR2(9 BYTE),
     "NUMERO" NUMBER(5,0),
     "LOGRADOURO" VARCHAR2(255 BYTE),
     "BAIRRO" VARCHAR2(255 BYTE),
     "LOCALIDADE" VARCHAR2(100 BYTE),
     "UF" VARCHAR2(2 BYTE),
     "COMPLEMENTO" VARCHAR2(255 BYTE),
     "LATITUDE" NUMBER(10,7),
     "LONGITUDE" NUMBER(10,7)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TB_EONET3
--------------------------------------------------------

CREATE TABLE "GLOBAL"."TB_EONET3"
(	"ID_EONET" NUMBER,
     "JSON" CLOB,
     "DATA" TIMESTAMP (6) WITH LOCAL TIME ZONE,
     "EONET_ID" VARCHAR2(50 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
REM INSERTING into GLOBAL.TB_CLIENTECONTATO3
SET DEFINE OFF;
REM INSERTING into GLOBAL.TB_CLIENTEENDERECO3
SET DEFINE OFF;
REM INSERTING into GLOBAL.TB_CLIENTE3
SET DEFINE OFF;
REM INSERTING into GLOBAL.TB_CONTATO3
SET DEFINE OFF;
REM INSERTING into GLOBAL.TB_ENDERECOEVENTOS3
SET DEFINE OFF;
REM INSERTING into GLOBAL.TB_ENDERECO3
SET DEFINE OFF;
REM INSERTING into GLOBAL.TB_EONET3
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TB_ENDERECOEVENTOS3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_ENDERECOEVENTOS3_PK" ON "GLOBAL"."TB_ENDERECOEVENTOS3" ("TB_ENDERECO3_ID_ENDERECO", "TB_EONET3_ID_EONET")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CLIENTE3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_CLIENTE3_PK" ON "GLOBAL"."TB_CLIENTE3" ("ID_CLIENTE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_EONET3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_EONET3_PK" ON "GLOBAL"."TB_EONET3" ("ID_EONET")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CLIENTECONTATO3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_CLIENTECONTATO3_PK" ON "GLOBAL"."TB_CLIENTECONTATO3" ("TB_CLIENTE3_ID_CLIENTE", "TB_CONTATO3_ID_CONTATO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CLIENTEENDERECO3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_CLIENTEENDERECO3_PK" ON "GLOBAL"."TB_CLIENTEENDERECO3" ("TB_CLIENTE3_ID_CLIENTE", "TB_ENDERECO3_ID_ENDERECO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_CONTATO3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_CONTATO3_PK" ON "GLOBAL"."TB_CONTATO3" ("ID_CONTATO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TB_ENDERECO3_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GLOBAL"."TB_ENDERECO3_PK" ON "GLOBAL"."TB_ENDERECO3" ("ID_ENDERECO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TB_CLIENTE3_ID_CLIENTE_TRG
--------------------------------------------------------

CREATE OR REPLACE EDITIONABLE TRIGGER "GLOBAL"."TB_CLIENTE3_ID_CLIENTE_TRG" BEFORE
    INSERT ON tb_cliente3
    FOR EACH ROW
     WHEN ( new.id_cliente IS NULL ) BEGIN
    :new.id_cliente := tb_cliente3_id_cliente_seq.nextval;
END;

/
ALTER TRIGGER "GLOBAL"."TB_CLIENTE3_ID_CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TB_CONTATO3_ID_CONTATO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GLOBAL"."TB_CONTATO3_ID_CONTATO_TRG" BEFORE
    INSERT ON tb_contato3
    FOR EACH ROW
     WHEN ( new.id_contato IS NULL ) BEGIN
    :new.id_contato := tb_contato3_id_contato_seq.nextval;
END;

/
ALTER TRIGGER "GLOBAL"."TB_CONTATO3_ID_CONTATO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TB_ENDERECO3_ID_ENDERECO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GLOBAL"."TB_ENDERECO3_ID_ENDERECO_TRG" BEFORE
    INSERT ON tb_endereco3
    FOR EACH ROW
     WHEN ( new.id_endereco IS NULL ) BEGIN
    :new.id_endereco := tb_endereco3_id_endereco_seq.nextval;
END;

/
ALTER TRIGGER "GLOBAL"."TB_ENDERECO3_ID_ENDERECO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TB_EONET3_ID_EONET_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GLOBAL"."TB_EONET3_ID_EONET_TRG" BEFORE
    INSERT ON tb_eonet3
    FOR EACH ROW
     WHEN ( new.id_eonet IS NULL ) BEGIN
    :new.id_eonet := tb_eonet3_id_eonet_seq.nextval;
END;

/
ALTER TRIGGER "GLOBAL"."TB_EONET3_ID_EONET_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CONTATO3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("ID_CONTATO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("DDD" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("TELEFONE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("CELULAR" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("WHATSAPP" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("EMAIL" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" MODIFY ("TIPO_CONTATO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CONTATO3" ADD CONSTRAINT "TB_CONTATO3_PK" PRIMARY KEY ("ID_CONTATO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ENDERECOEVENTOS3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_ENDERECOEVENTOS3" MODIFY ("TB_ENDERECO3_ID_ENDERECO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECOEVENTOS3" MODIFY ("TB_EONET3_ID_EONET" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECOEVENTOS3" ADD CONSTRAINT "TB_ENDERECOEVENTOS3_PK" PRIMARY KEY ("TB_ENDERECO3_ID_ENDERECO", "TB_EONET3_ID_EONET")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CLIENTECONTATO3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_CLIENTECONTATO3" MODIFY ("TB_CLIENTE3_ID_CLIENTE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTECONTATO3" MODIFY ("TB_CONTATO3_ID_CONTATO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTECONTATO3" ADD CONSTRAINT "TB_CLIENTECONTATO3_PK" PRIMARY KEY ("TB_CLIENTE3_ID_CLIENTE", "TB_CONTATO3_ID_CONTATO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CLIENTEENDERECO3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_CLIENTEENDERECO3" MODIFY ("TB_CLIENTE3_ID_CLIENTE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTEENDERECO3" MODIFY ("TB_ENDERECO3_ID_ENDERECO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTEENDERECO3" ADD CONSTRAINT "TB_CLIENTEENDERECO3_PK" PRIMARY KEY ("TB_CLIENTE3_ID_CLIENTE", "TB_ENDERECO3_ID_ENDERECO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_EONET3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_EONET3" MODIFY ("ID_EONET" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_EONET3" MODIFY ("EONET_ID" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_EONET3" ADD CONSTRAINT "TB_EONET3_PK" PRIMARY KEY ("ID_EONET")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CLIENTE3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_CLIENTE3" MODIFY ("DATA_NASCIMENTO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTE3" MODIFY ("SOBRENOME" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTE3" MODIFY ("DOCUMENTO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTE3" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTE3" MODIFY ("NOME" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_CLIENTE3" ADD CONSTRAINT "TB_CLIENTE3_PK" PRIMARY KEY ("ID_CLIENTE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ENDERECO3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("ID_ENDERECO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("CEP" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("NUMERO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("LOGRADOURO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("BAIRRO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("LOCALIDADE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("UF" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("COMPLEMENTO" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("LATITUDE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" MODIFY ("LONGITUDE" NOT NULL ENABLE);
ALTER TABLE "GLOBAL"."TB_ENDERECO3" ADD CONSTRAINT "TB_ENDERECO3_PK" PRIMARY KEY ("ID_ENDERECO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_CLIENTECONTATO3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_CLIENTECONTATO3" ADD CONSTRAINT "TB_CLIENTECONTATO3_TB_CLIENTE3_FK" FOREIGN KEY ("TB_CLIENTE3_ID_CLIENTE")
    REFERENCES "GLOBAL"."TB_CLIENTE3" ("ID_CLIENTE") ENABLE;
ALTER TABLE "GLOBAL"."TB_CLIENTECONTATO3" ADD CONSTRAINT "TB_CLIENTECONTATO3_TB_CONTATO3_FK" FOREIGN KEY ("TB_CONTATO3_ID_CONTATO")
    REFERENCES "GLOBAL"."TB_CONTATO3" ("ID_CONTATO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_CLIENTEENDERECO3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_CLIENTEENDERECO3" ADD CONSTRAINT "TB_CLIENTEENDERECO3_TB_CLIENTE3_FK" FOREIGN KEY ("TB_CLIENTE3_ID_CLIENTE")
    REFERENCES "GLOBAL"."TB_CLIENTE3" ("ID_CLIENTE") ENABLE;
ALTER TABLE "GLOBAL"."TB_CLIENTEENDERECO3" ADD CONSTRAINT "TB_CLIENTEENDERECO3_TB_ENDERECO3_FK" FOREIGN KEY ("TB_ENDERECO3_ID_ENDERECO")
    REFERENCES "GLOBAL"."TB_ENDERECO3" ("ID_ENDERECO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_ENDERECOEVENTOS3
--------------------------------------------------------

ALTER TABLE "GLOBAL"."TB_ENDERECOEVENTOS3" ADD CONSTRAINT "TB_ENDERECOEVENTOS3_TB_ENDERECO3_FK" FOREIGN KEY ("TB_ENDERECO3_ID_ENDERECO")
    REFERENCES "GLOBAL"."TB_ENDERECO3" ("ID_ENDERECO") ENABLE;
ALTER TABLE "GLOBAL"."TB_ENDERECOEVENTOS3" ADD CONSTRAINT "TB_ENDERECOEVENTOS3_TB_EONET3_FK" FOREIGN KEY ("TB_EONET3_ID_EONET")
    REFERENCES "GLOBAL"."TB_EONET3" ("ID_EONET") ENABLE;
